### PR TITLE
Add Win32Raw printer to available printers

### PR DESCRIPTION
**Pull request by ramonpoca**
### Contributor checklist

- [X] I have read the CONTRIBUTING.rst
- [X] I have tested my contribution on these devices:
 * Windows 10 w. simulator
- [x] My contribution is ready to be merged as is

----------

### Description

Hi there,
I've added a basic implementation of a win32 printer-queue based printing support. I believe that would be nicer than the current libusb juggling.

Right now I've tested it manually using several simulators. I hope to have a real printer soon. :)

### CODE REVIEW

**Comment by patkan** [comment]
Thank you for your contribution and sorry for the long delay. I will try to check your PR as soon as possible.

**Comment by patkan** [comment]
Hi @ramonpoca,
did you get around to testing it with a real printer?

**Comment by ramonpoca** [comment]
Yep, in fact we're using it.

**Comment by patkan** [comment]
OK, great. Thank you for the information!

**Pull request merged**
