### PR TITLE
Linespacing

### PR DESCRIPTION
**Pull request by miracle2k**
### Contributor checklist

- [x] I have read the CONTRIBUTING.rst
- [x] I have tested my contribution on these devices: Epson TM-T88IIIP
- [x] My contribution is ready to be merged as is

----------

### CODE REVIEW

**Comment by patkan** [comment]
Hi Michael,
thank you very much for your contributions.
This one seems to fail for Python versions over 2. Let me know if you need help with fixing this.

Generally: could you please generate your PRs against the development-branch? This way we can assemble everything there, update the changelog and then release.

**Comment by miracle2k** [comment]
Thinking about it more, you're right. It doesn't make sense to expose the underlying ESC commands literally. I'm not sure what the best technical term is for the function argument; divisor, denominator, base... - I'm just going to pick one of them for now.

**Comment by patkan** [comment]
This can be merged now, can't it?

**Comment by miracle2k** [comment]
I believe so.

**Pull request merged**
