### PR TITLE
Ean example fix

### LINKED ISSUE #350: Invalid EAN in examples after API v3
I have:
- [X] searched open and closed issues for duplicates

### Bug description
In the process of implementing #176, python-escpos has the implemented the desirable feature of checking for validity on EAN barcodes before attempting to print them.  This has caused the unintended consequence of breaking the examples which use the value `1324354657687` which is not an EAN valid value due to the incorrect checksum on the last digit.

### Steps to reproduce
- Use the example code with the value `1324354657687`

### Device info
N/A

<!-- since version 2.0.1 you can type 'python-escpos version' in your shell.
 **python-escpos version:** 3.0a6

 **python version:** 3.7.3

 **operating system:** Debian Buster ARMv7l (Raspbian)

### PR DESCRIPTION
**Pull request by brianredbeard**
### Contributor checklist

- [X] I have read the CONTRIBUTING.rst
- [X] I have tested my contribution on these devices:
 * Sewoo WTP-150 (Emulating Epson TM-88)
- [X] My contribution is ready to be merged as is

----------

### Description

In the various examples and python-escpos CLI there are a number of uses
of `13243546557687` as an EAN-13 example.  This EAN barcode is invalid
as the checksum should be `0` and not `7`.

```
$ python test_print.py
Traceback (most recent call last):
  File "test_print.py", line 5, in <module>
    p.barcode('13243546557687', 'EAN13', 64, 2, '', '')
  File "/home/pi/fatt-display/lib/python3.7/site-packages/escpos/escpos.py", line 433, in barcode
    bc=bc,
escpos.exceptions.BarcodeCodeError: No Barcode code was supplied (Barcode '13243546557687' not in a valid format for type 'EAN13')
```

This patch set removes `13243546557687` and replaces it with the valid
number `40063813339310`.

In researching the list of [assigned prefixes issued by
G1][g1-prefixes] there seemed to be no "officially" defined test  prefix, so
this change was made to be minimally invasive using the number from the
existing test cases.

Resolves #350

Affects #176

[g1-prefixes]: https://www.gs1.org/standards/id-keys/company-prefix
[test-code]: https://www.barcodelookup.com/4006381333931

### CODE REVIEW

**Comment by brianredbeard** [comment]
Closing this to re-order the commits to support the CI checks around authors.

**Comment by patkan** [comment]
@brianredbeard should I just reopen this one?

**Comment by patkan** [comment]
I am just testing something, because on my system it also works...

**Comment by patkan** [comment]
OK, I am not completely sure what the problem here actually is or was, but if you take in a68347ee1c47608be0c8c5abc2c08b7d8991a4ff (I have created a branch in this repository) the CI-job should pass.

**Pull request closed without merging**
