### PR TITLE
Adding barcode function type B and additional barocdes. 

### PR DESCRIPTION
**Pull request by DavisGoglin**
Added the option to print barcodes using barcode function type B, requested in issue #85.

I tried to match documentation and test as best I could. I don't have a printer that supports type B. 

As a side note, I'm not sure if we are sending a `NUL` at the end of barcode function type A as is specified in the sec linked.

### CODE REVIEW

**Comment by patkan** [comment]
Thank your very much. One thing that I saw: I think it has to be `CODABAR` not `CODEBAR` (https://en.wikipedia.org/wiki/Codabar).
Apart from that: I don't think I have such a printer either. Maybe someone has? @Loafdude, do you have a printer that supports Type B?

**Comment by Loafdude** [comment]
I have a TM-T88V.
From it's specs it should support type B but I cannot get your implementation to work.

That said I can only get type A working with a few of the barcodes.
For example code
    e.text("UPC-A\n")
    e.barcode('132435465768','UPC-A',function_type="A")
    e.text("UPC-E\n")
    e.barcode('127890','UPC-E',function_type="A")
    e.text("EAN13\n")
    e.barcode('1324354657687','EAN13',function_type="A")
    e.text("EAN8\n")
    e.barcode('13243546','EAN8',function_type="A")
    e.text("CODE39\n")
    e.barcode('*TEST*','CODE39',function_type="A")
    e.text("ITF\n")
    e.barcode('55867492279103','ITF',function_type="A")
    e.text("NW7\n")
    e.barcode('31117013206375','NW7',function_type="A")
    e.text("CODE93\n")

Working: UPC-A, EAN13, EAN8, CODE39.
Non-Working: UPC-E, ITF, NW7

When I set the type to "B" the working barcodes no longer work.
They print the barcode 'code' variable unformatted just in standard font. 
No attempt at barcode printing is done. No whitespace, nothing. 

Please add a note to the docs that code39 needs * character at beginning and the end of the data for it to print.

Thanks for working on this.

**Comment by Loafdude** [comment]
test

**Comment by Loafdude** [comment]
Type B on the left, Type A on the right.

Note that the printer in eating some of my text() methods. 
There should be a EAN13 above the second barcode. Type UPC-E is eating that data
Type ITF seems to be eating the N from NW7 text. 

Perhaps the printer is still trying to accept data for these formats.
Not sure on type B. I took a look at the reference but don't have time to debug it.

**Comment by DavisGoglin** [comment]
See if the workaround in issue #58 works to fix any of the type A barcodes - adding a `\x00` at the end of the barcode data.

**Comment by Loafdude** [comment]
That fixed them except the NW7.
That might be a problem with my data though.

\0 should not affect the Function B stuff though. Seems it has a length field in the reference.

**Comment by DavisGoglin** [comment]
If I'm reading the spec right, `e._raw('1d6b650a31323334353637383930'.decode('hex'))` should print a UPC-A barcode of 1234567890. 

- `1D` = `GS` Control character
- `6B` = 'k', barcode command
- `65` = Barcode type UPC-A
- `0A` = 11 characters in the barcode data
- `31323334353637383930` = 1234567890, barcode data

What happens when you print the above?

**Comment by Loafdude** [comment]
Nope thats not working.
Same result as on the left in the image

**Comment by DavisGoglin** [comment]
The only other think I can think of is `e._raw('1d6b410a31323334353637383930'.decode('hex'))`, if 65 is the decimal and we should be sending hex, `41`.

**Comment by Loafdude** [comment]
just tried it no go

**Comment by Loafdude** [comment]
e._raw('1D6B410B3030303030303030303030'.decode('hex'))
works

investigating

**Comment by Loafdude** [comment]
Alright. Here is the two working lengths for UPC-A

e._raw('1D6B410C303030303030303030303030'.decode('hex'))
e._raw('1d6b410b3132333435363738393030'.decode('hex'))

**Comment by DavisGoglin** [comment]
I made a stupid mistake above. I translated `0A` to 11, not 10. So the code I was sending wasn't spec because it was too short of a barcode.

**Comment by Loafdude** [comment]
e.text("UPC-A\n")
    e.barcode('13243546576','UPC-A',function_type="A")
    e.text("UPC-E\n")
    e.barcode('132435','UPC-E',function_type="A")
    e.text("EAN13\n")
    e.barcode('1324354657687','EAN13',function_type="A")
    e.text("EAN8\n")
    e.barcode('13243546','EAN8',function_type="A")
    e.text("CODE39\n")
    e.barcode('*TEST*','CODE39',function_type="A")
    e.text("ITF\n")
    e.barcode('55867492279103','ITF',function_type="A")
    e.text("NW7\n")
    e.barcode('A00000000A','NW7',function_type="A")
    e.text("UPC-A\n")
    e.barcode('13243546576','UPC-A',function_type="B")
    e.text("UPC-E\n")
    e.barcode('132435','UPC-E',function_type="B")
    e.text("EAN13\n")
    e.barcode('1324354657687','EAN13',function_type="B")
    e.text("EAN8\n")
    e.barcode('13243546','EAN8',function_type="B")
    e.text("CODE39\n")
    e.barcode('*TEST*','CODE39',function_type="B")
    e.text("ITF\n")
    e.barcode('55867492279103','ITF',function_type="B")
    e.text("NW7\n")
    e.barcode('A00000000A','NW7',function_type="B")
    e.text("CODE93\n")
    e.barcode('1324354657687','CODE93',function_type="B")
    e.text("CODE128 Type A\n")
    e.barcode('{A*TEST*','CODE128',function_type="B")
    e.text("CODE128 Type B\n")
    e.barcode('{B*TEST*','CODE128',function_type="B")
    e.text("CODE128 Type C\n")
    e.barcode('{C*TEST*','CODE128',function_type="B")
    e.text("GS1-128\n")
    e.barcode('00123456780000000001','GS1_128',function_type="B")
    e.text("GS1 DataBar Omnidirectional\n")
    e.barcode('0000000000000','GS1 DataBar Omnidirectional',function_type="B")
    e.text("GS1 DataBar Truncated\n")
    e.barcode('0000000000000','GS1 DataBar Truncated',function_type="B")
    e.text("GS1 DataBar Limited\n")
    e.barcode('0000000000000','GS1 DataBar Limited',function_type="B")
    e.text("GS1 DataBar Expanded\n")
    e.barcode('00AAAAAAA','GS1 DataBar Expanded',function_type="B")
    e.cut()

test

**Comment by Loafdude** [comment]
Great seems to be working.

GS1-128 is in the docs but your code uses GS1_128 in the dictionary key. Needs a typo fix

Code128 requires setup in the string. We should handle it because it is escpos specific
I would add a CODE128_TYPEA, B and C mode to the dictionary.
append to the end of the string {<mode> before the code (ie. {A, {B, {C)

Other barcodes are quirky. my TM-T88V enforces some requirements on them before it will print. Not all requirements are documented though.
GS1-128 has specific length configuration or something despite the escpos docs saying it can be 2-255. I could not get short strings to print.
GS1-Databar Expanded has a mode set with the first two characters (this is part of spec i believe)
GS1 Databar limited must have a 0 or 1 for the first character (this is part of spec i believe)

Good job. Nice to have that working!

**Comment by patkan** [comment]
I just tested the "demo-code" and those that are supported by my printer (T88II) print fine in A and B mode.

Thank you very much to both of you for your effort.
I think we can merge this as soon as the few minor issues @Loafdude pointed out are fixed.

**Comment by DavisGoglin** [comment]
Added fixes. 

The barcode code above should probably be put into a demo/tests somewhere, but I'll wait until something like fix-image-printing gets merged before I try to figure out how to write this version of tests.

**Comment by patkan** [comment]
OK, looks good to me. I will merge this.

Yes, we should add tests, but I am still not that sure which test framework to use (currently nose, maybe switch to nose2) and how to best write tests for escpos-code. (Probably the best way would be to compose the command as a string from the reference and then compare the output with this reference, but I am open for better propositions.)

**Comment by DavisGoglin** [comment]
In my mind the best method for testing is with you mentioned: get a known good hex output, print to a file, and compare them. 

The only other feature I'd like is to find an easy to way to print to a physical printer for tests.

**Pull request merged**
