### PR TITLE
release v3.0a5

### PR DESCRIPTION
**Pull request by patkan**

### CODE REVIEW

**Comment by om26er** [comment]
Thank you for the release and subsequent pre-release update on pypi.

**Comment by om26er** [comment]
Also, I have just found https://github.com/python-escpos/python-escpos/milestone/5 -- is that *all* that needs to be fixed before 3.0 stable release ?

Either way, I will be helping to get 3.0 released as stable.

**Comment by patkan** [comment]
Thank you for asking :-)
I will go through the issues and try to see if there should be anything added from my point of view. Basically I would like to include all current changes of the API in v3. On the other hand, release numbers are not made of gold and should we need a v4, we can have a v4 ;-)

In #176 we tried to discuss what could be changed. The other issues are more something that just has to be done.

**Comment by patkan** [comment]
As far as I see it, the milestone should be cleaned up now, @om26er. In case you would like to work on any issue, feel free to pick it up :-)

**Pull request merged**
