### PR TITLE
Enable Windows Support

### LINKED ISSUE #299: Is windows 10 supported - getting usb_detach_kernel_driver_np error
Is it true that python-escpos 3.0a3 is not compatible with windows 10 - as [this stackoverflow comment ](https://stackoverflow.com/questions/35248718/attributeerror-function-usb-detach-kernel-driver-np-not-found) suggests?  And as suggested by the [python-escpos todo readme](http://python-escpos.readthedocs.io/en/latest/user/todo.html)?

```
from escpos import *
Epson = printer.Usb(0x04b8, 0x0e03)
```

I get the error `function 'usb_detach_kernel_driver_np' not found`.  

Am running Python 3.6.  Printer Epson TM-TS20.  Am running in vmware, windows 10 (hosted by a mac).  I can attatch the Epson printer to the windows virtual machine ok and print to it using the official Epson drivers etc.

Re python-escpos on windows 10, I worked around the lack of /tmp directory (saw there was a fix for this recently merged - nice) by simply creating a c:/tmp directory.  Then I ran into missing backend issues, and as I couldn't find libusb on the system after `pip install pyusb` thus assumed that I needed to find and install these backend dlls myself.  There are several confusing choices as to where to get these dlls from and how to install them.  I copied libusb dlls into windows/system32 using both the zadig installer and also by copying in the dlls downloaded from https://libusb.info/.
My normal Epson TM-TS20 driver (via ESDPRT001) seems to have been broken by the zadig step (which created a printer on port USB001). I currently have these dlls: (list made using git bash shell which is why it look Linux-like):

```
-rwxr-xr-x 1 Andy 197121  76384 May 17 19:06 /c/windows/system32/libusb0.dll*
-rwxr-xr-x 1 Andy 197121 121856 Mar 25 12:00 /c/windows/system32/libusb-1.0.dll*
-rw-r--r-- 1 Andy 197121  46686 Mar 25 12:00 /c/windows/system32/libusb-1.0.lib
-rw-r--r-- 1 Andy 197121 904192 Mar 25 12:00 /c/windows/system32/libusb-1.0.pdb
-rwxr-xr-x 1 Andy 197121  99128 May 17 19:06 /c/windows/system32/libusbk.dll*
```

So do I have a bad dll situation or is it simply that python-escpos 3.0a3 is not currently compatible with windows 10 and I should stop wasting my time trying to get this to work, till windows 10 is officially supported?

### LINKED ISSUE #316: How to work with windows 7
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
I am trying to work with Epson POS TM-82 printer on windows 7 (64 bit). I have installed the printer's driver. I have python 2.7.15 (64 bit) installed. To work with python I am using this package, python-escpos.

### Steps to reproduce
After I have installed python-escpos, and try to run as documented, I am getting an error:

```
from escpos.printer import Usb
Usb(0x04b8, 0x0e11)
```

> usb.core.NoBackendError: No backend available

1. After some more digging, I found [this wiki page](https://github.com/libusb/libusb/wiki/Windows), according to this I need to Use the most recent version of Zadig, an Automated Driver Installer GUI application for WinUSB, libusb-win32 and libusbK.

    So, I downloaded Zadig; from the drop-down menu selected TM-82, and chose WinUSB to replace the driver and installed the driver succesfully.

    After that again I ran the same python-escpos documented command from above, and got the same error:

    > usb.core.NoBackendError: No backend available

2. After some more research I found [this answer on stackoverflow](https://stackoverflow.com/questions/33972145/pyusb-on-windows-8-1-no-backend-available-how-to-install-libusb/34720024#34720024). 
    So following the answer, I downloaded the libusb zip file, and copied `libusb-1.0.20_2\MS64\dll\libusb-1.0.lib` to my `C:\Windows\System32`. And finally copied` libusb-1.0.20_2\MS64\static\libusb-1.0.lib` to `C:\Python27\libs\`

    After that again I ran the same python-escpos documented command from above, and this time I got a different error:

    > NotImplementedError: Operation not supported or unimplemented on this platform

What am I missing here? Could you please help me. Thank you.

### Device info

 **Printer:** Epson POS TM-82

 **python-escpos version:** 2.2.0

 **python version:** 2.7.15 (64 bit)

 **operating system:** windows 7 (64 bit)

### PR DESCRIPTION
**Pull request by om26er**
### Contributor checklist

- [x] I have read the CONTRIBUTING.rst
- [x] I have tested my contribution on these devices:
 * XPrinter XP-E200L
- [x] My contribution is ready to be merged as is

----------

### Description
`is_kernel_driver_active()` and `detach_kernel_driver()` are only implemented in `libusb1` this change makes this library work with `libusb0` as well, which is installed by [zadig](https://zadig.akeo.ie/) on Windows. 

Edit:
closes #274 
fixes #316 
fixes #299

### CODE REVIEW

**Comment by om26er** [comment]
ping @patkan

**Comment by patkan** [comment]
Hi @om26er thank you for your contribution and sorry for the delay!
This means with this patch it is possible to just use one python usb library (contrary to the proposed changes in #274)

Does one have to watch out for anything when setting up python-escpos on windows? Should we link to any documentation from our docs?

**Comment by om26er** [comment]
@patkan, it worked pretty easily for us. We did a clean install of Windows 7 and 10 (for testing), used Zadig and installed the WinUSB driver using it and monkey patched the change I propose here.

**Comment by patkan** [comment]
OK, sounds good to me.
I have updated your branch with a fix for the CI-job and would merge if it passes

**Comment by om26er** [comment]
Seems the CI passed except for the codecov stuff (likely unrelated to my change ?)

**Comment by patkan** [comment]
Yes. It is somewhat related: you added new lines of code and that diff is not covered. But that is OK...

**Comment by patkan** [comment]
Thank you for the contribution again :-)

**Comment by om26er** [comment]
Thanks for landing this, do you think it would make sense to tag a new release and upload to pypi ?

**Comment by patkan** [comment]
Yes, definitely. I will see into merging the rest of the open PRs and then tag and upload a new release in order to make it available.

**Comment by semiautomatix** [comment]
I am going to need some assistance here, as I am not coming right. 

I'm running python Python 3.7.3 and I've tried using both WinUSB and libusb-win32 (libusb0.dll) to access my printer.

` import traceback

 from escpos.printer import Usb

 p = Usb(0x4b43, 0x3538, in_ep=0x82, out_ep=0x2)
 try:
     p.text("Hello World\n")
 except Exception as err:
     print(traceback.format_exc())`

WinUSB

---------------------------------------------------------------------------
USBNotFoundError                          Traceback (most recent call last)
<ipython-input-19-9fc9beeed1b6> in <module>
      4
      5 """ Seiko Epson Corp. Receipt Printer (EPSON TM-T88III) """
----> 6 p = Usb(0x4b43, 0x3538, in_ep=0x82, out_ep=0x2)
      7 try:
      8     p.text("Hello World\n")

c:\python37\lib\site-packages\escpos\printer.py in __init__(self, idVendor, idProduct, usb_args, timeout, in_ep, out_ep, *args, **kwargs)
     55         if idProduct:
     56             usb_args['idProduct'] = idProduct
---> 57         self.open(usb_args)
     58
     59     def open(self, usb_args):

c:\python37\lib\site-packages\escpos\printer.py in open(self, usb_args)
     64         self.device = usb.core.find(**usb_args)
     65         if self.device is None:
---> 66             raise USBNotFoundError("Device not found or cable not plugged in.")
     67
     68         self.idVendor = self.device.idVendor

USBNotFoundError: USB device not found (Device not found or cable not plugged in.)

libusb-win32

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\usb\core.py", line 223, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-20-9fc9beeed1b6>", line 8, in <module>
    p.text("Hello World\n")
  File "c:\python37\lib\site-packages\escpos\escpos.py", line 514, in text
    self.magic.write(txt)
  File "c:\python37\lib\site-packages\escpos\magicencode.py", line 272, in write
    self.write_with_encoding(encoding, to_write)
  File "c:\python37\lib\site-packages\escpos\magicencode.py", line 293, in write_with_encoding
    six.int2byte(self.encoder.get_sequence(encoding)))
  File "c:\python37\lib\site-packages\escpos\printer.py", line 102, in _raw
    self.device.write(self.out_ep, msg, self.timeout)
  File "c:\python37\lib\site-packages\usb\core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "c:\python37\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "c:\python37\lib\site-packages\usb\core.py", line 215, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "c:\python37\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "c:\python37\lib\site-packages\usb\core.py", line 225, in get_interface_and_endpoint
    for intf in self.get_active_configuration(device):
  File "c:\python37\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "c:\python37\lib\site-packages\usb\core.py", line 239, in get_active_configuration
    bConfigurationValue=self.backend.get_configuration(self.handle)
  File "c:\python37\lib\site-packages\usb\backend\libusb0.py", line 510, in get_configuration
    100)
  File "c:\python37\lib\site-packages\usb\backend\libusb0.py", line 593, in ctrl_transfer
    timeout
  File "c:\python37\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: The system cannot find the file specified.\r\n\n'

The .dll and .lib files from libusb-win32-bin-1.2.6.0 and libusb-1.0.22 are either in the C:\Windows\SysWOW64 folder or the C:\Windows\System32 folder.

Any advice?

**Comment by junglegao** [comment]
I have the same issue, swith to use libusbk in windows7 can solve it, http://libusbk.sourceforge.net/UsbK3/index.html

**Comment by Davidamgad2** [comment]
Hello @junglegao 

I'm using windows 10 and having the same issue that @semiautomatix has.

I'm new to this usb libraries and not sure what to do could you please tell?
image

Thanks in advance!

**Pull request merged**
