### PR TITLE
Started refactor of the set method

### PR DESCRIPTION
**Pull request by MicroJoe**
### Contributor checklist

- [x] I have read the CONTRIBUTING.rst
- [x] I have tested my contribution on these devices:
 * Tested refactor using hand-created tests for before-and-after regression avoidance
- [x] My contribution is ready to be merged as is

----------

### Description

This is a work in progress addressing the #96 issue.

I am starting it here in order to see if people are interested in this before further development. This allows the set method to be tested (I will write the tests before modifying a feature, then refactor, then rerun the test).

### CODE REVIEW

**Comment by MicroJoe** [comment]
Note that this PR will break the current set API, but this seems to be ok since final 0.3 is not released yet and still open to API breaks.

**Comment by MicroJoe** [comment]
I have finished the refactoring, and added tests than could run on the previous set method and that passes on the new set method too.

I have edited the PR to mark it as ready to merge since I have finalised the PR. Feedbacks very welcome.

**Comment by MicroJoe** [comment]
Requesting a review for this PR (ping @patkan?)

I refactored using the dict structure mentionned in the issue, but could not factorize out the write in a for loop because of handling the special cases that would make the code unlegible.

**Comment by MicroJoe** [comment]
Ok, I think I get it now. What I have wrote will be the coming `layout` method, and we will have to create a `set` method that is a bit smarter than that. This is a startpoint for future PRs I guess.

I did not test this on my printer, is there a script that tries everything on the printer so we can detect bugs? Or should I run some manual tests using the `set` method?

I am also thinking of some refactor around the `size` parameter to be splitted into two boolean properties: `double_width=False` and `double_height=False` by default. Doing so will avoid string parameters and use booleans that are easier to reason about.

**Comment by patkan** [comment]
Unfortunately there is no test script. A good place to keep something like this would be the examples folder.
Since this is more of a refactoring than a real change of "escpos-code" testing on a real printer is not that essential, I just wanted to try it out.

Creating more booleans is a good one. This also makes auto-completition and similar stuff easier.

**Comment by MicroJoe** [comment]
Here is the booleans commit. I think I will stop here for this PR and start to work on other issues.

**Comment by patkan** [comment]
Sorry, I've been busy.
It got around to trying it out and it looks good. Thank you!

**Comment by MicroJoe** [comment]
> It got around to trying it out and it looks good. Thank you!

Maybe you should add your test code to the examples directory for other people to test their printers against text formatting.

Thanks for the merge!

**Comment by patkan** [comment]
I would like to, but I tested by playing around in a ipython shell.
I will try to think of writing a script next time.

**Pull request merged**
