### PR TITLE
Rewrite image handling

### PR DESCRIPTION
**Pull request by mike42**
This pull request is to include a port of the image handling routines that I've been working on. It adds the option to select from three image print commands (`ESC *`, `GS v 0`, `GS ( L`), using two output formats (raster & column format), and with selectable print density. This is exposed via the CLI.

Tested on TM-U220 and TM-T20 from Epson, but because the test cases are ported as well, [a good variety](https://github.com/mike42/escpos-php/blob/96f05cbf460f5b67c2184ee4e91aedfbcedeb788/README.md#printers) of printers will work. It also add s a 'Dummy' printer for use in tests, which saves on disk writes and will let tests run in parallel if the remaining tests are updated.

I benchmarked the new routines against a variety of test images, and the replacement raster formatting is around 26x faster (see #42 for detail). By removing the current code, compatibility with `pypy3` is also gained.

----

The update command-line usage of `image` is-

````
usage: cli.py image [-h] --img_source IMG_SOURCE
                    [--impl {bitImageRaster,bitImageColumn,graphics}]
                    [--high_density_horizontal HIGH_DENSITY_HORIZONTAL]
                    [--high_density_vertical HIGH_DENSITY_VERTICAL]
````

Example prints of [tux.png](https://cloud.githubusercontent.com/assets/2080552/14315164/00918804-fc3f-11e5-8538-454215403518.png):

image

Printers vary in support for their commands. The Epson TM-T20 (receipt on lower right) can print with all of the supported commands.

````
python3 -m escpos.cli -c t20.yml image --img_source tux.png --impl graphics
````

ZJ 5890 (receipt in the upper right) does not support graphics commands. The raster bit image (`GS v 0`) remains the default, because it is widely implemented.

````
python3 -m escpos.cli -c 5890.yml image --img_source tux.png
````

And TM-U220 only supports low density, column format bit images. That is the huge penguin on the left-

````
python3 -m escpos.cli -c u220.yml image --img_source tux.png --impl=bitImageColumn --high_density_vertical False --high_density_horizontal False
````
----
Issues possibly addressed-
- #42
- #46 
- #79
- #109
- #64

### CODE REVIEW

**Comment by mike42** [comment]
Updates pending: need some CLI/output examples as a comment here, and the docstrings that QuantifiedCode is after.

**Comment by patkan** [comment]
Thank you! I am currently a bit low on time and would like to have a close look at it. I hope I have time this weekend or start of next week. (And I would like to have it open until the weekend so more people could have a look at it.)

However, on the first glance the PR looks very good to me. Just one minor issue that I found from a quick read: There are some semicolons on the ends of lines. Could you please remove them as they are not needed? (I think I have overlooked a few in the last PR too)

**Comment by DavisGoglin** [comment]
There isn't really any major disadvantage to using a `Dummy` printer compared to `BytesIO` combined with a `File` printer, is there?

It's a lot easier to work with, and I can't think of many problems that would be caught using `File` with a fake file that wouldn't be caught with `Dummy`.

**Comment by patkan** [comment]
Just an idea for systems with low computing power:
We could use [lrucache](https://docs.python.org/3/library/functools.html#functools.lru_cache). This way printing the same picture twice becomes faster. It should however be possible to disable this function (or we should make sure that usecases like calling the function with the same path but changed images behind this path are taken care of.)

**Comment by mike42** [comment]
Took out the semicolons, that's a PHP habit, sorry about that.

The python side of the image processing is quite fast on this branch, so I'm not sure there'e much room left for a dramatic improvement by adding caching.

| Action    | Python 2 | Python 3 |
|-----------------------------------------------|----------|----------|
| Print --help                                  | 0.16 s    | 0.11 s    |
| Print tulips (feature/rewrite-image-handling) | 0.17 s    | 0.13 s    |
| Print tulips (development)                    | 6.94 s    | 0.87 s    |

This is a print of [tulips.png](https://cloud.githubusercontent.com/assets/2080552/14351075/9bf30c1a-fd10-11e5-8440-6ee91ad54e52.png) to a file using this config:
````
printer:
  type: file
  devfile: path.bin
````
Script to help out with the comparison:
````
git checkout development
python3 -m compileall . > /dev/null
/usr/bin/time -f 'real %e' python3 -m escpos.cli -c file.yml image --path_img tulips.png
/usr/bin/time -f 'real %e' python3 -m escpos.cli --help

git checkout feature/rewrite-image-handling > /dev/null
python3 -m compileall . > /dev/null
/usr/bin/time -f 'real %e' python3 -m escpos.cli -c file.yml image --img_source tulips.png

git checkout development
python -m compileall . > /dev/null
/usr/bin/time -f 'real %e' python -m escpos.cli -c file.yml image --path_img tulips.png
/usr/bin/time -f 'real %e' python -m escpos.cli --help

git checkout feature/rewrite-image-handling > /dev/null
python -m compileall . > /dev/null
/usr/bin/time -f 'real %e' python -m escpos.cli -c file.yml image --img_source tulips.png
````

**Comment by patkan** [comment]
I just tested it myself, the most time seems to be taken by the transmission of the image.
I will test this somewhen on a Raspi in order to see whether the reduced computing power is an issue there but for now caching is definitely not necessary.

You remove the functions fullimage and direct_image. As I see the functionality of direct_image is replaced by calling image with a PIL-object. However, scaling images isn't really supported anymore. Or is it? (However, I am not that sure if we even need that.)
Printing loooong images seems to work, I tested that.

My printer (T88II) prints faint lines in both bitImage-modes. (Just like in some issues here) I still don't quite get whether this is fixable or not. Can you explain this effect to me?

**Comment by mike42** [comment]
I think `full_image` was out of place, since we don't know how many pixels wide the printer is (the three printers I tested with have different widths)


Regarding unwanted lines in column format printing-

- Each row of 24 pixels is handled as a long character, and there are literally line breaks between the rows. The printer usually stitches these back together with no gaps.
- I have observed on my TM-T20, that the print speed adjusts based on the darkness of a row (printing solid black is slower than solid white), so one theory is that the change in darkness causes horizontal lines- I see them spaced every 24px on some long photo-like images, but not on black/white logos.
- Some lines are sort of expected in a line-based print mode

In the raster modes-
- The code in the development branch seems to pause at fixed intervals during printing, leaving white lines at places it stopped (is it sending multiple print commands? Not sure). This replacement code writes a whole blob at once, so the source if the lines is probably different to the open bugs.
- I don't see this on my printers, maybe a PNG file, code snippet and scanned receipt would allow proper debugging.

In any case, Epson recommends graphics commands,  which you can now use!

**Comment by patkan** [comment]
Thank you for your elaboration.

I am printing with an Epson TM-T88II. Since this thing is ancient it does not support the graphics command. (At least I assume that is the case. It simply does nothing and I have not yet managed to get a command reference for exactly this model.)
The lines are probably due to unprecise line-feeding by my printer (maybe that's a problem of the model, maybe a problem of worn out transports.) I was just curious whether this could be somehow improved.

See below my tests with tulips and tux on this branch. Tux just prints fine and tulips has lines that differ between the two modes.

image: [tulips.png](https://cloud.githubusercontent.com/assets/2080552/14351075/9bf30c1a-fd10-11e5-8440-6ee91ad54e52.png) (and [tux.png](https://cloud.githubusercontent.com/assets/2080552/14315164/00918804-fc3f-11e5-8538-454215403518.png))
```python
from escpos import printer
p = printer.Serial("/dev/ttyUSB1", baudrate="19200")
p.set(align="center")
p.text("tulips.png in different modes on Epson TM-T88II\n")
p.text("\n")
p.text("bitImageRaster\n")
p.image("tulips.png", impl="bitImageRaster")
p.text("graphics\n")
p.image("tulips.png", impl="graphics")
p.text("bitImageColumn\n")
p.image("tulips.png", impl="bitImageColumn")
p.cut()
```
output:
* [tulips](https://cloud.githubusercontent.com/assets/4189642/14444617/ebd57a72-0046-11e6-9d1f-67119814f8c0.jpg)
* [tux](https://cloud.githubusercontent.com/assets/4189642/14444616/ebd3b66a-0046-11e6-8d64-f034ef6982e1.jpg)

**Comment by patkan** [comment]
For the Pull request:
I have just read the code in detail. I like it very much, clearly structured and very readable.
I have found some issues (mostly nitpicky stuff). I have created a [patch](https://github.com/python-escpos/python-escpos/files/214082/pr_issues.patch.zip). (Mostly about whitespace-usage in function-definitions)
Feel free to do with this whatever you want ;-)
(I will polish the repository one way or another before releasing v1.1 so that is consistently formatted.)

All in all, I will merge this (if you do not find any problems with my last post, I just assume it is a problem of my printer). Please tell me when I should merge and then I will do so with this PR.

**Comment by mike42** [comment]
Just applied one final bug fix to the low-density modes. I think this is ready to merge.

Possible future work on image handling might include:
- tweak things like print density and speed to see if we can get better quality
- use download graphics/ NV graphics for speed
- use the jumbo-graphics command to allow even larger images to be sent on printers that can handle it
- use zero-length line feeds to print both red and black to to a row on impact printers

--
For comparison with your output, I don't get lines on the code in this PR. Full snippet-

````python
from escpos import printer
p = printer.File("/dev/usb/lp0")

p.set(align="center")
p.text("tux.png in different modes on Epson TM-T20\n")
p.text("\n")
p.text("bitImageRaster\n")
p.image("tux.png", impl="bitImageRaster")
p.text("graphics\n")
p.image("tux.png", impl="graphics")
p.text("bitImageColumn\n")
p.image("tux.png", impl="bitImageColumn")
p.cut()

p.set(align="center")
p.text("tulips.png in different modes on Epson TM-T20\n")
p.text("\n")
p.text("bitImageRaster\n")
p.image("tulips.png", impl="bitImageRaster")
p.text("graphics\n")
p.image("tulips.png", impl="graphics")
p.text("bitImageColumn\n")
p.image("tulips.png", impl="bitImageColumn")
p.cut()
````

Output:

- [tm-t20-test-print](https://cloud.githubusercontent.com/assets/2080552/14492992/4f6a7648-01c6-11e6-93f3-0dfa07e4a7fd.jpg)

On the `development` branch, I get the lines as reported in #64 and #48

````
python -m escpos.cli -c t20.yml image --path_img tulips.png
python -m escpos.cli -c t20.yml image --path_img tux.png
````

- [tm-t20-test-print2](https://cloud.githubusercontent.com/assets/2080552/14493557/62f164d0-01c9-11e6-91c6-707c499edeb0.jpg)

**Comment by patkan** [comment]
The behaviour of my printer seems to be somewhat different. The lines do not change much between the branches. However, your printing function improves printing nevertheless and this is probably connected to my printer being awkward.
I will merge your PR now, thank you for your contribution.

**Comment by lite1979** [comment]
I just started following you today on GitHub @mike42 , but I've been reading through your image progress for quite a while hoping to get some insight into a problem I'm having. We have an image converter for ESCP that works very well with my Epson TM-T88V, but does not work with our Star TSP650. It prints the garbled text mentioned by ClickworkOrange back in October. Would you mind telling me what made the difference for the TM-U220? I feel it may be what's preventing me from printing an image on my Star printer.  Here is our image handing:  tray/src/qz/printer/ImageWrapper.java Hopefully you can see it.

**Comment by mike42** [comment]
@lite1979 - Of the three image output commands implemented here, the TM-U220 supports only `ESC *`, which I refer to as column-format bit images. Because it's a low density impact printer, the U220 further requires the low density setting, which is unlikely to be necessary on your printer.

If you're looking to debug your TSP650 in more detail, I'd suggest taking this driver for a spin and posting any issues on the bug tracker, or even sending your printer some binary graphics/bit image [test output](https://github.com/mike42/escpos-php/tree/56afef6601a702b152c7fef8ee992a9cc383bf9d/test/integration/resources/output) to get an idea of whether this output will work or your hardware.

**Pull request merged**
