### PR TITLE
Weather Forecast Example Script

### PR DESCRIPTION
**Pull request by mrwunderbar666**
### Contributor checklist

- [x] I have read the CONTRIBUTING.rst
- [x] I have tested my contribution on these devices:
 * ZJ5890T Cheap Printer
- [x] My contribution is ready to be merged as is

----------

### Description
I have created another example script that prints out the weather forecast

### CODE REVIEW

**Comment by patkan** [comment]
Thank your for your PR :-)

Does the MI T license also apply to the icons? Could you please group the files in a subdirectory of `examples` and clarify the license for the images?

**Comment by MicroJoe** [comment]
This would be an idiomatic example to include!

About the licensing, quoting from the climacons repository:

> You are free to use any of the Climacons Icons (the "icons") in any personal or commercial work without obligation of payment (monetary or otherwise) or attribution, however a credit for the work would be appreciated. Do not redistribute or sell and do not claim creative credit. Intellectual property rights are not transferred with the download of the icons.

So I think this is fine to include in the project as long as we mention where the icons come from, like putting a `README.md` linking to his GH and website in the icons directory (something like `examples/graphics/climaicons/README.md`).

**Comment by mrwunderbar666** [comment]
Thanks for the feedback!

I have made the requested changes, but I cannot figure out why the flake8-check doesn't pass. Maybe because the example script doesn't have an API key specified.

**Comment by MicroJoe** [comment]
There are > 10 flake8 errors, they are not related to API keys IMO but just related to the syntax of your code. You can see all the warnings here for commit f983c62: https://travis-ci.org/python-escpos/python-escpos/jobs/259221618#L431. You can access this information by clicking on the build details on Travis in order to see why flake8 failed.

**Comment by belono** [comment]
@mrwunderbar666 you can use [autopep8](https://pypi.python.org/pypi/autopep8) to fix this minor spaces issues on your local repo:

``
pip install autopep8
``

then

``
autopep8 --in-place -a ./examples/weather.py
``

Is a handy tool and quite safe at this aggression level.

**Comment by patkan** [comment]
Thank you for your contribution!

**Comment by mrwunderbar666** [comment]
Thanks for all your feedback!
I just got started with Python a month ago and your tips helped me to write better and cleaner code!

**Pull request merged**
