### PR TITLE
Feature/check barcodes

### PR DESCRIPTION
**Pull request by derlin**
### Contributor checklist

- [X] I have read the CONTRIBUTING.rst
- [X ] I have tested my contribution on these devices: 
    * espon TM-T20II
- [X] My contribution is ready to be merged as is

----------

### Description

__Add a method to check the validity of a barcode code__

The validation process is the following:

1. check the length of the code,
2. check the characters and format of the code

Those checks are mainly performed using regexp and based on the ESC/POS specification (see [ESC/POS Command Specifications 4-122],
(http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf). This means that valid code from the barcode standard perspective might be invalid from the ESC/POS perspective and vice-versa. 

__Automatically perform the check in the `barcode()` method__

If the check fails, a `BarcodeCodeError` is raised.

__Add a parameter to disable the check in the `barcode()` method__

Add a parameter `check` (default to True). If the user want to experiment with invalid codes, he can do so but at his expenses.

### Going further

It might be nice to add support for checksums as well. 

For example, given an EAN-13 barcode code, if the code length is 12, the `barcode` method could automatically add the checksum digit. 

The problems/questions I see are:

* how about codes with a wrong checksum ?
* how about barcode standards with
     - optional checksums ?
     - variable length ?

### CODE REVIEW

**Comment by derlin** [comment]
It seems like the commit udpating the AUTHORS list is the one failing. Is there something else to do other than running `doc/generate_authors.sh` command ?

**Comment by patkan** [comment]
Hi @derlin, thanks for the contribution!

There's still some problems with the authors-check :-(
You can try to merge the current development-branch in (I just pushed a commit). Please check if this commit generates a AUTHORS-file that will pass the check. (I assume that the default settings for sort might be different)

**Comment by patkan** [comment]
I just checked, if you run `./doc/generate_authors.sh` now, it should generate the file that Travis is expecting.
It might still be the case that your system handles this different. So if it does not work: could you please write which system you are using. Then I can try to research the problem.

**Comment by derlin** [comment]
Ok, it worked. Thanks !

**Comment by patkan** [comment]
@MicroJoe proposed in #100 to use the check_barcode-method of viivakoodi. This would be a bit contrary to this PR. What do you both (@MicroJoe and @derlin) think?

Since this is a rather contained commit, I would merge this like this. The benefit of this solution is that we can print barcodes without relying on a external library (and thus could make viivakoodi optional)

**Comment by derlin** [comment]
In my opinion, it is important to ensure that a code the printer won't be able to render throws an exception. Concerning the checksum and more thorough checks, letting them to the responsibility of the user (many barcode types have only optional checks, some standards like EAN-13 have many variations...) is fine by me. Indeed, it would complexify a lot the code and can be restrictive to some users that just need barcodes for internal purposes. 

What bothers me with the current solution though is the potential difference between the actual barcode and its associated text. 

For example, calling the `barcode` function with the EAN-13 barcode `13243546576` will print the barcode `132435465762` (the ending digit `2` is the checksum computed automatically by the printer), while the printed text is still `13243546576`. 

Another example is the CODE39 standard:
```python
printer.barcode('CODE39', '*WIKIPEDIA*')
printer.barcode('CODE39', 'WIKIPEDIA')
```
Both calls print the same barcode (the start and end characters '*' are automatically added), but the text is different...

What I would propose:

* add a link to the barcode library @MicroJoe mentioned in the documentation
* automatically add checksum to the text _if it is missing_ for EAN and UPC (EAN-13 with only 12 digits -> add checksum)
* automatically add the '*' start/stop characters for CODE39 if missing
* (? make the `compute_checksum` public ?)

I am not sure about other standards, I would need to check.

**Comment by patkan** [comment]
Sorry for taking so long. I got around to have a deeper look at your PR and merged it.
Thank you for your contribution!

**Pull request merged**
