### PR TITLE
Passed Exception message to the CashDrawerError class

### PR DESCRIPTION
**Pull request by rakeshgunduka**
### Contributor checklist

- [x] I have read the CONTRIBUTING.rst
- [ ] I have tested my contribution on these devices:
 * e.g. Epson TM-T88II
- [x] My contribution is ready to be merged as is

----------

### CODE REVIEW

**Comment by belono** [comment]
Hi @rakeshgunduka.
I suggest to catch a `TypeError` in place of the general `Exception` to solve #267 .

`TypeError` is the exception raised for non int args:

`self.Epson._raw(_CASH_DRAWER('string1', 'string2', 'string3'))`
_CASH_DRAWER = lambda esc, p, m, t1=50, t2=50: six.int2byte(esc) + six.int2byte(p) + six.int2byte(m) + six.int2byte(t1) + six.int2byte(t2)
TypeError: an integer is required

and for wrong number of args:

`self.Epson._raw(_CASH_DRAWER(27, 112, 0, 64, 54, 54))`
TypeError: <lambda>() takes at most 5 arguments (6 given)

also for both wrong number of non int args:

`self.Epson._raw(_CASH_DRAWER('string'))`
TypeError: <lambda>() takes at least 3 arguments (1 given)

**Comment by rakeshgunduka** [comment]
Hi Beleno,
Thanks for the explanation. I am on it.

**Comment by belono** [comment]
Great!
Just one little thing.
In python, descriptive variable names are preferred, so, if you don't mind, you could rename the variable `e` as `error` or similar. ;)

**Comment by rakeshgunduka** [comment]
Yeah renamed the aliasing as 'err' which is short and descriptive.

**Comment by belono** [comment]
Looks great for me ;)
Thanks a lot.

**Comment by patkan** [comment]
Hi @rakeshgunduka thanks for the PR!
Could you please update the authors-file according to https://github.com/python-escpos/python-escpos/blob/development/CONTRIBUTING.rst#author-list? This is why the integration check is currently failing.

**Comment by rakeshgunduka** [comment]
Hi @belono ,
Some checks are still unsuccessful, can you give me a hint where is it failing. Or is it something which can be ignored?

**Comment by patkan** [comment]
This test indicates that you have no test-coverage for this functionality. In order to get this away you could write a test, which provokes this error and then checks whether this exception gets raised. A test that does something similar is in https://github.com/python-escpos/python-escpos/blob/development/test/test_function_barcode.py#L35-L36

**Comment by rakeshgunduka** [comment]
Hi @belono ,
This may take some time. I am having some problems in setting up and run the test cases.

**Comment by patkan** [comment]
I have added a little test to the PR.
Thank you!

**Pull request merged**
